// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLy6NwhZ65qW0jfTyJpvCb2GViw9rK8yQ',
    appId: '1:363326974019:web:b76b76943e9493f04fccf6',
    messagingSenderId: '363326974019',
    projectId: 'we-chat-39c57',
    authDomain: 'we-chat-39c57.firebaseapp.com',
    storageBucket: 'we-chat-39c57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQv9It-8tTXPsKel3mlI2EUPpoQmOS8Po',
    appId: '1:363326974019:android:dd8c8ea8db71b6d64fccf6',
    messagingSenderId: '363326974019',
    projectId: 'we-chat-39c57',
    storageBucket: 'we-chat-39c57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkW9EZs2jU78Tkzhl25c0mL146j-g6ZA',
    appId: '1:363326974019:ios:5622230cb7a4b7094fccf6',
    messagingSenderId: '363326974019',
    projectId: 'we-chat-39c57',
    storageBucket: 'we-chat-39c57.appspot.com',
    androidClientId: '363326974019-oml6nrgm1jim7ojotjfjfs0ad65r2bev.apps.googleusercontent.com',
    iosClientId: '363326974019-j2dlpguejsdltmd9ejlm107aoscuu214.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
